# Generated by Django 4.0 on 2022-01-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
